export const left = [
  {
    title:'创建故障工单',
    icon:'el-icon-tickets',
    path:'Risk'
  },
  {
    title:'创建检修工单',
    icon:'el-icon-notebook-1',
    path:'Other',
    params:{type:'service'}
  },
  {
    title:'事件提报',
    icon:'el-icon-upload2',
    path:'Event'
  },
  {
    title:'变更区域风险清单',
    icon:'el-icon-news',
    path:'Area'
  },
  {
    title:'变更作业风险清单',
    icon:'el-icon-postcard',
    path:'Operation'
  },
  {
    title:'编制检修计划',
    icon:'el-icon-edit',
    path:'Plan'
  }
]

export const right = [
  {
    title:'创建临时性工单',
    icon:'el-icon-notebook-2',
    path:'Other',
    params:{type:'temporary'}
  },
  { 
    title:'创建普查整改工单',
    icon:'el-icon-zoom-in',
    path:'Other',
    params:{type:'survey'}
  },
  {
    title:'故障修复延期申请',
    icon:'el-icon-pie-chart',
    path:'Extension'
  },
  {
    title:'生成故障报告',
    icon:'el-icon-document',
    path:'Report'
  }
]